/*
    Generated by Atomist on 13 07 2016 
*/
package demo;

import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
* Spring Java configuration file for Movies.
* Don't even think of using XML.
*/
@Configuration
public class MoviesConfiguration {

    // Your beans go here ... 
	// Atomist Bot suggests "maybe use an Atomist project editor to add a sample one?"
    @Bean
    public MovieService buildMovieService(){
        return new DefaultMovieService();
    }

    @Bean
    @ConditionalOnMissingBean
    public ParentalControlLevels buildInitialLevel(){
        return ParentalControlLevels.LEVEL_U;
    }

    @Bean
    public ParentalCheckerService buildParentCheckerService(ParentalControlLevels initialLevel,MovieService movieService){
        return new DefaultParentalCheckerService(initialLevel,movieService);
    }
}
