/*
    Generated by Atomist on 13 07 2016 
*/
package demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class MovieAccessController {

    private final ParentalCheckerService parentalCheckerService;

    @Autowired
    public MovieAccessController(final ParentalCheckerService parentalCheckerService) {
        this.parentalCheckerService = parentalCheckerService;
    }


    @RequestMapping(path = "/movie/{id}")
    public ResponseEntity<String> getParentalControlLevel(@PathVariable String id) {

        try {
            parentalCheckerService.checkMovieById(id);
            return new ResponseEntity<>("You may watch the movie", HttpStatus.OK);
        }
        catch (NotAllowedException e){
            return new ResponseEntity<>(e.getMessage(), HttpStatus.FORBIDDEN);
        } catch (TitleNotFoundException | TechnicalFailureException e) {
            return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
        }
    }

}